apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: cert
spec:
  secretName: tsmr-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: theyseemeroling.danmcclain.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - theyseemeroling.danmcclain.net
      - api.theyseemeroling.danmcclain.net
