apiVersion: apps/v1
kind: Deployment
metadata:
  name: theyseemeroling-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: theyseemeroling-api
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: theyseemeroling-api
    spec:
      imagePullSecrets:
      - name: githubcred
      containers:
      - name: discord-bot
        image: docker.pkg.github.com/danmcclain/theyseemeroling/discord:GITSHA
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: tsmr-env-vars-b65dbf7dd5
              key: discord_token.txt
