name: Central resources

on: 
  push:
    branches:
    - master
    paths:
    - 'config/*'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Update central resources
    steps:
    - uses: actions/checkout@v1
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show dmc-kube-1-15 > $GITHUB_WORKSPACE/.kubeconfig
    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig apply -f $GITHUB_WORKSPACE/config
