name: Integration

on: 
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish docker image
    steps:
    - uses: actions/checkout@v1
    - name: Authorize docker client
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_AUTH_TOKEN }}
      run: docker login docker.pkg.github.com -u danmcclain -p $GITHUB_TOKEN
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/danmcclain/theyseemeroling/discord:${{github.sha}}
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/danmcclain/theyseemeroling/discord:${{github.sha}}
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show dmc-kube-1-15 > $GITHUB_WORKSPACE/.kubeconfig
    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: $GITHUB_WORKSPACE/.kubeconfig
        context: do-nyc1-dmc-kube-1-15
      id: setcontext
    - uses: Azure/k8s-deploy@v1
      with:
        manifests: |
            deployment.yaml
        images: docker.pkg.github.com/danmcclain/theyseemeroling/discord:${{github.sha}}
        kubectl-version: 'v1.15.3'
    
