name: Integration

on: 
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish docker image
    steps:
    - uses: actions/checkout@v1
    - name: Authorize docker client
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_AUTH_TOKEN }}
      run: docker login docker.pkg.github.com -u danmcclain -p $GITHUB_TOKEN
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/danmcclain/theyseemeroling/discord:${{github.sha}}
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/danmcclain/theyseemeroling/discord:${{github.sha}}
    - name: Update deployment.yaml
      run: sed -i 's|GITSHA|${{github.sha}}|' $GITHUB_WORKSPACE/deployment.yaml
    - name: Inspect dep 
      run: echo $GITHUB_WORKSPACE/deployment.yaml
    
