name: Frontend Master Deploy

on: 
  push:
    branches:
    - master
    paths:
    - 'frontend/**'
    - 'config/webapp/**'
    - '.github/workflows/frontend.yml'

jobs:
  publish:
    runs-on: ubuntu-latest
    name: Publish docker image
    env:
      working-dir: ./frontend
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - run: yarn install
      working-directory: ${{env.working-dir}}
    - run: yarn build
      name: Build
      working-directory: ${{env.working-dir}}
    - name: Authorize docker client
      env:
        GITHUB_TOKEN: ${{ secrets.DOCKER_AUTH_TOKEN }}
      run: docker login docker.pkg.github.com -u danmcclain -p $GITHUB_TOKEN
      working-directory: ${{env.working-dir}}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker.pkg.github.com/danmcclain/theyseemeroling/frontend:${{github.sha}}
      working-directory: ${{env.working-dir}}
    - name: Push the Docker image
      run: docker push docker.pkg.github.com/danmcclain/theyseemeroling/frontend:${{github.sha}}
    - name: Update deployment.yaml
      run: sed -i 's|GITSHA|${{github.sha}}|' $GITHUB_WORKSPACE/config/webapp/deployment.yml
    - name: Save DigitalOcean kubeconfig
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_ACCESS_TOKEN }}
      with:
        args: kubernetes cluster kubeconfig show dmc-kube-1-15 > $GITHUB_WORKSPACE/.kubeconfig

    - name: Deploy to DigitalOcean Kubernetes
      run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig apply -Rf $GITHUB_WORKSPACE/config/webapp

    - name: Verify deployment
      run: kubectl --kubeconfig=$GITHUB_WORKSPACE/.kubeconfig rollout status deployment/theyseemeroling-webapp
    
